### ISSUE TITLE
ModelServerCompoundCommand is missing its CommandKind in field type

### ISSUE THREAD

**Issue by ndoschek** [eclipse-emfcloud/emfcloud-modelserver-theia#30]
During #28 came up, that the `ModelServerCompoundCommand` provides a type, which equals `CommandKind.COMPOUND` (= 'compound'). This field is not set, when receiving updates form the `ModelServer`.
Please evaluate, if we need to customize the default Json ObjectMapper that the command type is properly set or we have to initialize this field on the client.

- Anyways, the interfaces `ModelServerCommand` and `ModelServerCompoundCommand` should be implemented as classes to be able to initialize fields (e.g. the type of the `ModelServerCompoundCommand`).
- Please also consider moving the helper methods of `ModelServerCommandUtil` to the dedicated class implementations.

**Comment by martin-fleck-at** [comment]
@ndoschek: I believe the type was not serialized properly since it was the default enum value (`0`). However, we now switched to a different command strcuture where the type is simply a String that should always be serialized. Could you please verify if there is still something that needs to be adapted or whether we can close this task? Thank you!

**Comment by ndoschek** [comment]
I double checked and the types are correctly set with the new command structure :heavy_check_mark:
