### ISSUE TITLE
Create generic CustomCommandUtil

### ISSUE THREAD

**Issue by ndoschek** [eclipse-emfcloud/emfcloud-modelserver-theia#38]
The functionality to use custom commands was added as an example in #35 .
It would be great to add a generic `CustomCommandUtil` or a `CustomCommand` type in `model-server-api.ts`.

**Comment by martin-fleck-at** [comment]
@ndoschek Great idea! What kind of common functionality do you envision for custom commands? There is definitely a need to have a command creation utility so that the users do not always have to specify the same eClass (`http://www.eclipsesource.com/schema/2019/modelserver/command#//Command`). Other than that, I am not sure what custom command will have in common besides that they will probably will make use of properties more than other commands.

**Comment by ndoschek** [comment]
Yes I agree, atm we cannot offer much additional functionality except the eClass specification.
So I think offering a basic constructor which takes the `type` and the `properties` structure should be sufficient for now.
For the properties we could use a map of strings to be more flexible, what do you think?
