### ISSUE TITLE
DiagnosticManager does not populate the problems view

### ISSUE THREAD

**Issue by sgraband** [eclipse-emfcloud/emfcloud-modelserver-theia#67]
When trying to set the diagnostics to the problems view via the DiagnosticManager the problems view is never actually populated.
After debugging i found out, that this line always results in false:
https://github.com/eclipse-emfcloud/emfcloud-modelserver-theia/blob/50a35e15acb706c961ee492afee64dabb531fa0a/modelserver-markers-theia/src/browser/diagnostic-manager.ts#L62

This prevents the diagnostics to be put into the problems view.

Is there any reason, why a simple undefined check is not enough? The `converted` object should already be `LangServerDiagnostic | undefined`.

I tested it and just using `if(converted)` works.

**Comment by tortmayr** [comment]
I also had a look. We cannot reuse `LangServerDiagnostic.is(converted)` here. The typeguard check fails because  it expects a "range" property with positive start and end indexes. However, in our case the indexes are -1 because we only rely on the uriFragment  for deriving  the correct position.

As a @sgraband  already mentioned a simply undefined-check should suffice here. We will fix this as part of #65

**Comment by martin-fleck-at** [comment]
@tortmayr Sorry, I was already working on this and just pushed a PR. Maybe we can review and merge that?
